model_select: DistanceParser
seed: 1234
weight_decay: 0.000001
window_size: 2
pos_embed_dim: 400
word_embed_dim: 400
hidden_dim: 1200
lr: 0.001
sepc: 0
epc: 100
drop: 0.3
drope: 0.1
dropr: 0.2
word_layer: 2
word_bid: true
arc_layer: 2
arc_bid: true
savepath: /home/user_data/baoy/experiments/parser/distance_parser
datapath: /home/user_data/baoy/data/con/ptb/
filename: distance.origin
configpath: /home/user_data/baoy/projects/NJUParser-pytorch/configs/distance.yaml
dev_every: 450
log_every: 50
batch_size: 20
cuda: true
eval_path: /home/user_data/baoy/projects/NJUParser-pytorch/EVALB
patience: 6
factor: 0.8
beta1: 0.9
beta2: 0.995