model_select: TransformerDistanceParser
seed: 1234
weight_decay: 0.000001
window_size: 2
pos_embed_dim: 112
word_embed_dim: 400
hidden_dim: 512
inner_hid_dim: 1024
lr: 0.001
sepc: 0
epc: 10000
drop: 0.3
drope: 0.1
dropr: 0.2
word_layer: 6
arc_layer: 3
n_head: 8
savepath: /home/user_data/baoy/experiments/parser/distance_parser
datapath: /home/user_data/baoy/data/con/ptb/
filename: distance.transformer
configpath: /home/user_data/baoy/projects/NJUParser-pytorch/configs/distance.yaml
dev_every: 300
log_every: 25
batch_size: 50
cuda: true
eval_path: /home/user_data/baoy/projects/NJUParser-pytorch/EVALB
patience: 6
factor: 0.8
beta1: 0.9
beta2: 0.995